version: 2

builds:
  - main: ./cmd/gw
    ldflags:
      - -s -w -X main.version={{.Tag}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz

changelog:
  use: github
