version: 2

builds:
  - main: ./cmd/gw
    ldflags:
      - -s -w -X main.version={{.Tag}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz

brews:
  - repository:
      owner: gin0606
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/gin0606/gw
    description: "Git worktree wrapper with lifecycle hooks"

changelog:
  use: github
